# Název workflow, zobrazí se v záložce "Actions" na GitHubu
name: Deploy to GitHub Pages

# Kdy se má workflow spustit
on:
  # Spustí se při push do větve "main"
  push:
    branches: [ "main" ]
  # Umožňuje spustit workflow i ručně z GitHubu
  workflow_dispatch:

# Oprávnění pro workflow, aby mohlo zapisovat na GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Definuje, že se bude spouštět pouze jeden build najednou
concurrency:
  group: "pages"
  cancel-in-progress: true

# Úlohy (jobs), které se mají provést
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Můžete použít verzi Node.js, kterou používáte
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Nahraje se obsah složky, kterou vytvoří `npm run build`
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4